controller_manager:
  ros__parameters:
    update_rate: 50  # Update rate for controller manager

    # Joint State Broadcaster Configuration
    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"
